###Local: HTML professional information
GET http://localhost:8080/

###Local: professional JSON
GET http://localhost:8080/professional

###Local: All contacts
GET http://localhost:8080/contacts

###Local: Single contact
GET http://localhost:8080/contacts/64588003bcf037d29c7d920e

###Live: HTML professional information
GET https://cse341-ns.onrender.com

###Live: professional JSON
GET https://cse341-ns.onrender.com/professional

###Live: All contacts
GET https://cse341-ns.onrender.com/contacts

###Live: Single contact
GET https://cse341-ns.onrender.com/contacts/64588003bcf037d29c7d920e

###Local: Insert contact
POST http://localhost:8080/contacts/insert HTTP/1.1
content-type: application/json

{
    "firstName":"Joss",
    "lastName":"Barragan",
    "email":"joss@gmail.com",
    "favoriteColor":"Black",
    "birthday":"July 17th"

}

###Local: Update contact
PUT http://localhost:8080/contacts/update/6467058df817f5a0b2ff8033 HTTP/1.1
content-type: application/json

{
    "firstName":"Joss",
    "lastName":"Barragan",
    "email":"joss@gmail.com",
    "favoriteColor":"Black",
    "birthday":"July 22th"

}

###Local: Delete contact
DELETE http://localhost:8080/contacts/delete/645c04b816a83f1df4c7431b HTTP/1.1




###Live: See All Contacts
GET https://cse341-ns.onrender.com/contacts HTTP/1.1
content-type: application/json

###Live: See One Contact
GET https://cse341-ns.onrender.com/contacts/64588003bcf037d29c7d920e HTTP/1.1
content-type: application/json


###Live: Insert contact
POST https://cse341-ns.onrender.com/contacts/insert HTTP/1.1
content-type: application/json

{
    "firstName":"Joss",
    "lastName":"Barragan",
    "email":"joss@gmail.com",
    "favoriteColor":"Black",
    "birthday":"July 17th"

}

###Live: Update contact
PUT https://cse341-ns.onrender.com/contacts/update/6467058df817f5a0b2ff8033 HTTP/1.1
content-type: application/json

{
    "firstName":"Joss",
    "lastName":"Barragan",
    "email":"joss@gmail.com",
    "favoriteColor":"Black",
    "birthday":"July 18th"

}

###Live: Delete contact
DELETE https://cse341-ns.onrender.com/contacts/delete/64670614f817f5a0b2ff8034 HTTP/1.1